spring.application.name=onefan-backend

spring.datasource.url=jdbc:postgresql://db.ywmtbodddiyzyndtcaif.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=$SupabaseOneFan
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# swagger ui url
springdoc.swagger-ui.path=/docs